export enum SliderNavigationPositionV2 {
  CENTER = 'center',
  TOP = 'top',
  BOTTOM = 'bottom',
  CENTER_LEFT = 'center-left',
  CENTER_RIGHT = 'center-right',
  CENTER_CENTER = 'center-center',
  TOP_LEFT = 'top-left',
  TOP_RIGHT = 'top-right',
  TOP_CENTER = 'top-center',
  BOTTOM_LEFT = 'bottom-left',
  BOTTOM_RIGHT = 'bottom-right',
  BOTTOM_CENTER = 'bottom-center',
  OUT_TOP_LEFT = 'out-top-left',
  OUT_TOP_RIGHT = 'out-top-right',
  OUT_TOP_CENTER = 'out-top-center',
  OUT_BOTTOM_LEFT = 'out-bottom-left',
  OUT_BOTTOM_RIGHT = 'out-bottom-right',
  OUT_BOTTOM_CENTER = 'out-bottom-center',
}

export const SliderNavigationPositionV2Options = [
  {value: SliderNavigationPositionV2.CENTER, title: 'Center'},
  {value: SliderNavigationPositionV2.TOP, title: 'Top'},
  {value: SliderNavigationPositionV2.BOTTOM, title: 'Bottom'},
  {value: SliderNavigationPositionV2.CENTER_LEFT, title: 'Center Left'},
  {value: SliderNavigationPositionV2.CENTER_RIGHT, title: 'Center Right'},
  {value: SliderNavigationPositionV2.CENTER_CENTER, title: 'Center Center'},
  {value: SliderNavigationPositionV2.TOP_LEFT, title: 'Top Left'},
  {value: SliderNavigationPositionV2.TOP_RIGHT, title: 'Top Right'},
  {value: SliderNavigationPositionV2.TOP_CENTER, title: 'Top Center'},
  {value: SliderNavigationPositionV2.BOTTOM_LEFT, title: 'Bottom Left'},
  {value: SliderNavigationPositionV2.BOTTOM_RIGHT, title: 'Bottom Right'},
  {value: SliderNavigationPositionV2.BOTTOM_CENTER, title: 'Bottom Center'},
  {value: SliderNavigationPositionV2.OUT_TOP_LEFT, title: 'Out Top Left'},
  {value: SliderNavigationPositionV2.OUT_TOP_RIGHT, title: 'Out Top Right'},
  {value: SliderNavigationPositionV2.OUT_TOP_CENTER, title: 'Out Top Center'},
  {value: SliderNavigationPositionV2.OUT_BOTTOM_LEFT, title: 'Out Bottom Left'},
  {
    value: SliderNavigationPositionV2.OUT_BOTTOM_RIGHT,
    title: 'Out Bottom Right',
  },
  {
    value: SliderNavigationPositionV2.OUT_BOTTOM_CENTER,
    title: 'Out Bottom Center',
  },
];
