import {
  GalleryType,
  HoverEffect,
  IGeneralSettings,
  ILightboxSettings,
  ImageClickAction,
  IMasonrySettings,
  ISlideshowSettings,
  IThumbnailSettings,
  LightboxImageAnimation,
  LightboxTextPosition,
  LightboxThumbnailsPosition,
  PaginationButtonShape,
  PaginationType,
  ThumbnailTitlePosition,
  TitleAlignment,
  TitlePosition,
  TitleVisibility,
} from 'data-structures';

const thumbnailMockSettings: IThumbnailSettings = {
  width: 150,
  height: 150,
  columns: 5,
  gap: 10,
  backgroundColor: 'White',
  containerPadding: 0,
  padding: 10,
  paddingColor: 'Skyblue',
  borderRadius: 5,
  titlePosition: ThumbnailTitlePosition.BOTTOM,
  titleAlignment: TitleAlignment.LEFT,
  titleVisibility: TitleVisibility.NONE,
  titleFontFamily: 'Roboto',
  titleColor: 'Black',
  titleFontSize: 20,
  hoverEffect: HoverEffect.BLUR,
  paginationType: PaginationType.SIMPLE,
};
const thumbnailMockSettings2: IThumbnailSettings = {
  width: 200,
  height: 250,
  columns: 3,
  gap: 10,
  backgroundColor: 'White',
  containerPadding: 0,
  padding: 10,
  paddingColor: 'Skyblue',
  borderRadius: 5,
  titlePosition: ThumbnailTitlePosition.BOTTOM,
  titleAlignment: TitleAlignment.LEFT,
  titleVisibility: TitleVisibility.NONE,
  titleFontFamily: 'Roboto',
  titleColor: 'Black',
  titleFontSize: 20,
  hoverEffect: HoverEffect.FLASH,
  paginationType: PaginationType.SIMPLE,
};

const generalMockSettings: IGeneralSettings = {
  orderBy: 'default',
  orderDirection: 'asc',
  itemsPerPage: 8,
  activeButtonColor: 'blue',
  inactiveButtonColor: 'inherit',
  paginationButtonShape: PaginationButtonShape.CIRCULAR,
  loadMoreButtonColor: 'blue',
  paginationTextColor: 'green',
  clickAction: ImageClickAction.LIGHTBOX,
  openUrlInNewTab: false,
  showSearchField: true,
  searchFieldPlaceholder: 'SEARCH',
};

const lightboxMockSettings: ILightboxSettings = {
  isFullscreen: false,
  width: 800,
  height: 800,
  areControlButtonsShown: false,
  isInfinite: false,
  padding: 15,
  canDownload: true,
  canZoom: true,
  isFullscreenAllowed: false,
  isSlideshowAllowed: false,
  autoplay: false,
  slideDuration: 3000,
  thumbnailsPosition: LightboxThumbnailsPosition.BOTTOM,
  thumbnailWidth: 80,
  thumbnailHeight: 80,
  thumbnailBorder: 2,
  thumbnailBorderRadius: 20,
  thumbnailBorderColor: 'white',
  thumbnailPadding: 0,
  thumbnailGap: 10,
  backgroundColor: '',
  textPosition: LightboxTextPosition.BOTTOM,
  textFontFamily: 'Roboto',
  textColor: 'White',
  imageAnimation: LightboxImageAnimation.BLUR,
  showTitle: true,
  titleFontSize: 20,
  titleAlignment: TitleAlignment.LEFT,
  showDescription: true,
  descriptionFontSize: 16,
  descriptionMaxRowsCount: 5,
};

const slideshowMockSettings: ISlideshowSettings = {
  width: 800,
  height: 800,
  isInfinite: false,
  padding: 15,
  autoplay: false,
  slideDuration: 3000,
  backgroundColor: '',
  textPosition: LightboxTextPosition.BOTTOM,
  textFontFamily: 'Roboto',
  textColor: 'White',
  imageAnimation: LightboxImageAnimation.BLUR,
  thumbnailsPosition: LightboxThumbnailsPosition.BOTTOM,
  thumbnailWidth: 80,
  thumbnailHeight: 80,
  thumbnailBorder: 2,
  thumbnailBorderRadius: 20,
  thumbnailBorderColor: 'white',
  thumbnailPadding: 0,
  thumbnailGap: 10,
  isSlideshowAllowed: true,
  showTitle: true,
  titleFontSize: 20,
  titleAlignment: TitleAlignment.LEFT,
  showDescription: true,
  descriptionFontSize: 16,
  descriptionMaxRowsCount: 5,
  isFullCoverImage: false,
};

const masonryMockSettings: IMasonrySettings = {
  width: 70,
  gap: 5,
  backgroundColor: '',
  containerPadding: 0,
  padding: 5,
  paddingColor: '',
  columns: 5,
  borderRadius: 5,
  titlePosition: TitlePosition.BOTTOM,
  titleAlignment: TitleAlignment.LEFT,
  titleVisibility: TitleVisibility.NONE,
  titleFontFamily: 'Roboto',
  titleColor: 'Black',
  titleFontSize: 20,
  hoverEffect: HoverEffect.BLUR,
  paginationType: PaginationType.SIMPLE,
};

const template1 = {
  id: '1',
  name: 'Thumbnail Default',
  type: GalleryType.THUMBNAILS,
  thumbnails: thumbnailMockSettings,
  general: generalMockSettings,
  lightbox: lightboxMockSettings,
};

const template2 = {
  id: '2',
  name: 'Slideshow Default',
  type: GalleryType.SLIDESHOW,
  slideshow: slideshowMockSettings,
};

const template3 = {
  id: '3',
  name: 'Masonry Default',
  type: GalleryType.MASONRY,
  masonry: masonryMockSettings,
};

const template4 = {
  id: '4',
  name: 'Thumbnail Big Items',
  type: GalleryType.THUMBNAILS,
  thumbnails: thumbnailMockSettings2,
  general: generalMockSettings,
  lightbox: lightboxMockSettings,
};

const template5 = {
  id: 'none',
  name: 'None',
};

export {template1, template2, template3, template4, template5};
