import {
  ActionURLSource,
  CaptionSource,
  DescriptionPosition,
  DescriptionSource,
  GalleryType,
  HoverEffect,
  IGeneralSettings,
  ILightboxSettings,
  ImageClickAction,
  IMasonrySettings,
  ISlideshowSettings,
  IThumbnailSettings,
  LightboxImageAnimation,
  LightboxTextPosition,
  LightboxThumbnailsPosition,
  PaginationType,
  Position,
  ThumbnailTitlePosition,
  TitleAlignment,
  TitlePosition,
  TitleSource,
  TitleVisibility,
} from 'data-structures';

const thumbnailMockSettings: IThumbnailSettings = {
  fillContainer: false,
  aspectRatio: '1.33',
  width: 150,
  height: 150,
  columns: 5,
  gap: 10,
  itemBorder: 0,
  itemBackgroundColor: '',
  itemBorderRadius: 0,
  backgroundColor: 'White',
  containerPadding: 0,
  padding: 10,
  paddingColor: 'Skyblue',
  borderRadius: 5,
  showTitle: false,
  titlePosition: ThumbnailTitlePosition.BOTTOM,
  captionPosition: ThumbnailTitlePosition.BOTTOM,
  titleSource: TitleSource.TITLE,
  titleAlignment: TitleAlignment.LEFT,
  captionVisibility: TitleVisibility.ALWAYS_SHOWN,
  titleVisibility: TitleVisibility.ALWAYS_SHOWN,
  titleFontFamily: 'Roboto',
  titleColor: 'Black',
  titleFontSize: 20,
  overlayTextBackground: 'rgba(0, 0, 0, 0.5)',
  invertTextColor: false,
  hoverEffect: HoverEffect.BLUR,
  paginationType: PaginationType.SIMPLE,
  showCaption: false,
  captionSource: CaptionSource.CAPTION,
  captionFontSize: 18,
  captionFontColor: 'Grey',
  showDescription: false,
  descriptionSource: DescriptionSource.DESCRIPTION,
  descriptionPosition: DescriptionPosition.BELOW,
  descriptionFontSize: 18,
  descriptionFontColor: 'Black',
  descriptionMaxRowsCount: 3,
};

const generalMockSettings: IGeneralSettings = {
  orderBy: 'default',
  orderDirection: 'asc',
  itemsPerPage: 8,
  activeButtonColor: 'blue',
  inactiveButtonColor: 'inherit',
  loadMoreButtonColor: 'blue',
  paginationTextColor: 'green',
  paginationButtonTextSize: 0.875,
  paginationButtonBorderRadius: 4,
  paginationButtonBorderSize: 0,
  paginationButtonBorderColor: '',
  loadMoreButtonText: '',
  paginationButtonClass: '',
  clickAction: ImageClickAction.LIGHTBOX,
  openUrlInNewTab: false,
  actionUrlSource: ActionURLSource.ACTIONURL,
  enableWatermark: false,
  watermarkImageURL: '',
  watermarkTransparency: 50,
  watermarkSize: 50,
  watermarkPosition: Position.MIDDLECENTER,
};

const lightboxMockSettings: ILightboxSettings = {
  isFullscreen: false,
  width: 800,
  height: 800,
  areControlButtonsShown: false,
  isInfinite: false,
  padding: 15,
  showCounter: true,
  canShare: false,
  canDownload: true,
  canZoom: true,
  isFullscreenAllowed: false,
  isSlideshowAllowed: false,
  autoplay: false,
  slideDuration: 3000,
  thumbnailsPosition: LightboxThumbnailsPosition.BOTTOM,
  thumbnailWidth: 80,
  thumbnailHeight: 80,
  thumbnailBorder: 2,
  thumbnailBorderRadius: 20,
  thumbnailBorderColor: 'white',
  thumbnailPadding: 0,
  thumbnailGap: 10,
  backgroundColor: '',
  textPosition: LightboxTextPosition.BOTTOM,
  textFontFamily: 'Roboto',
  textColor: 'White',
  imageAnimation: LightboxImageAnimation.BLUR,
  showTitle: true,
  titleFontSize: 20,
  titleAlignment: TitleAlignment.LEFT,
  showDescription: true,
  descriptionFontSize: 16,
  descriptionMaxRowsCount: 5,
  titleSource: TitleSource.TITLE,
  descriptionSource: DescriptionSource.DESCRIPTION,
  showCaption: false,
  captionSource: CaptionSource.CAPTION,
  captionFontSize: 18,
  captionFontColor: 'Grey',
};

const slideshowMockSettings: ISlideshowSettings = {
  width: 800,
  height: 800,
  isInfinite: false,
  padding: 15,
  autoplay: false,
  slideDuration: 3000,
  backgroundColor: '',
  textPosition: LightboxTextPosition.BOTTOM,
  textFontFamily: 'Roboto',
  textColor: 'White',
  imageAnimation: LightboxImageAnimation.BLUR,
  thumbnailsPosition: LightboxThumbnailsPosition.BOTTOM,
  thumbnailWidth: 80,
  thumbnailHeight: 80,
  thumbnailBorder: 2,
  thumbnailBorderRadius: 20,
  thumbnailBorderColor: 'white',
  thumbnailPadding: 0,
  thumbnailGap: 10,
  isSlideshowAllowed: true,
  showTitle: true,
  titleFontSize: 20,
  titleAlignment: TitleAlignment.LEFT,
  showDescription: true,
  descriptionFontSize: 16,
  descriptionMaxRowsCount: 5,
  isFullCoverImage: false,
  titleSource: TitleSource.TITLE,
  descriptionSource: DescriptionSource.DESCRIPTION,
  showCaption: false,
  captionSource: CaptionSource.CAPTION,
  captionFontSize: 18,
  captionFontColor: 'Grey',
};

const masonryMockSettings: IMasonrySettings = {
  width: 70,
  gap: 5,
  backgroundColor: '',
  containerPadding: 0,
  padding: 5,
  paddingColor: '',
  columns: 5,
  borderRadius: 5,
  titlePosition: TitlePosition.BOTTOM,
  captionPosition: TitlePosition.BOTTOM,
  titleSource: TitleSource.TITLE,
  titleAlignment: TitleAlignment.LEFT,
  titleVisibility: TitleVisibility.ALWAYS_SHOWN,
  captionVisibility: TitleVisibility.ALWAYS_SHOWN,
  titleFontFamily: 'Roboto',
  titleColor: 'Black',
  titleFontSize: 20,
  overlayTextBackground: 'rgba(0, 0, 0, 0.5)',
  invertTextColor: false,
  hoverEffect: HoverEffect.BLUR,
  paginationType: PaginationType.SIMPLE,
  showCaption: false,
  captionSource: CaptionSource.CAPTION,
  captionFontSize: 18,
  captionFontColor: 'Grey',
  showTitle: false,
};

const template1 = {
  id: '1',
  name: 'Thumbnail Default',
  type: GalleryType.THUMBNAILS,
  thumbnails: thumbnailMockSettings,
  general: generalMockSettings,
  lightbox: lightboxMockSettings,
};

const template2 = {
  id: '2',
  name: 'Slideshow Default',
  type: GalleryType.SLIDESHOW,
  slideshow: slideshowMockSettings,
};

const template3 = {
  id: '3',
  name: 'Masonry Default',
  type: GalleryType.MASONRY,
  masonry: masonryMockSettings,
};

const template4 = {
  id: '4',
  name: 'Thumbnail Big Items',
  type: GalleryType.THUMBNAILS,
  thumbnails: thumbnailMockSettings,
  general: generalMockSettings,
  lightbox: lightboxMockSettings,
};

const template5 = {
  id: 'none',
  name: 'None',
};

export { template1, template2, template3, template4, template5 };

