import {
  Direction,
  HoverEffect,
  ICarouselSettings,
  IGeneralSettings,
  ILightboxSettings,
  IMasonrySettings,
  IMosaicSettings,
  ISlideshowSettings,
  IThumbnailSettings,
  LightboxCaptionsPosition,
  LightboxImageAnimation,
  LightboxThumbnailsPosition,
  PaginationButtonShape,
  PaginationType,
  ThumbnailTitlePosition,
  TitleAlignment,
  TitlePosition,
  TitleVisibility,
} from 'data-structures';

const thumbnailMockSettings: IThumbnailSettings = {
  width: 150,
  height: 150,
  columns: 5,
  gap: 10,
  backgroundColor: 'White',
  padding: 10,
  paddingColor: 'Skyblue',
  borderRadius: 5,
  titlePosition: ThumbnailTitlePosition.BOTTOM,
  titleAlignment: TitleAlignment.LEFT,
  titleVisibility: TitleVisibility.NONE,
  titleFontFamily: 'Roboto',
  titleColor: 'Black',
  titleFontSize: 20,
  hoverEffect: HoverEffect.NONE,
  paginationType: PaginationType.SIMPLE,
};

const mosaicMockSettings: IMosaicSettings = {
  width: 70,
  direction: Direction.VERTICAL,
  gap: 5,
  backgroundColor: '',
  padding: 5,
  paddingColor: '',
  rowHeight: 250,
  columns: 5,
  borderRadius: 5,
  titlePosition: TitlePosition.BOTTOM,
  titleAlignment: TitleAlignment.LEFT,
  titleVisibility: TitleVisibility.NONE,
  titleFontFamily: 'Roboto',
  titleColor: 'Black',
  titleFontSize: 20,
  hoverEffect: HoverEffect.BLUR,
  paginationType: PaginationType.SIMPLE,
};

const masonryMockSettings: IMasonrySettings = {
  width: 70,
  gap: 5,
  backgroundColor: '',
  padding: 5,
  paddingColor: '',
  columns: 5,
  borderRadius: 5,
  titlePosition: TitlePosition.BOTTOM,
  titleAlignment: TitleAlignment.LEFT,
  titleVisibility: TitleVisibility.NONE,
  titleFontFamily: 'Roboto',
  titleColor: 'Black',
  titleFontSize: 20,
  hoverEffect: HoverEffect.BLUR,
  paginationType: PaginationType.SIMPLE,
};

const slideshowMockSettings: ISlideshowSettings = {
  width: 800,
  height: 800,
  isInfinite: false,
  padding: 15,
  autoplay: false,
  slideDuration: 3000,
  backgroundColor: '',
  captionsPosition: LightboxCaptionsPosition.BOTTOM,
  captionFontFamily: 'Roboto',
  captionColor: 'White',
  imageAnimation: LightboxImageAnimation.BLUR,
  thumbnailsPosition: LightboxThumbnailsPosition.BOTTOM,
  thumbnailWidth: 80,
  thumbnailHeight: 80,
  thumbnailBorder: 2,
  thumbnailBorderRadius: 20,
  thumbnailBorderColor: 'white',
  thumbnailPadding: 0,
  thumbnailGap: 10,
  isSlideshowAllowed: true,
};

const generalMockSettings: IGeneralSettings = {
  itemsPerPage: 8,
  activeButtonColor: 'blue',
  inactiveButtonColor: 'inherit',
  paginationButtonShape: PaginationButtonShape.CIRCULAR,
  loadMoreButtonColor: 'blue',
  paginationTextColor: 'green',
};

const lightboxMockSettings: ILightboxSettings = {
  showLightbox: true,
  isFullscreen: false,
  width: 800,
  height: 800,
  areControlButtonsShown: false,
  isInfinite: false,
  padding: 15,
  canDownload: true,
  canZoom: true,
  isFullscreenAllowed: false,
  isSlideshowAllowed: false,
  autoplay: false,
  slideDuration: 3000,
  thumbnailsPosition: LightboxThumbnailsPosition.BOTTOM,
  thumbnailWidth: 80,
  thumbnailHeight: 80,
  thumbnailBorder: 2,
  thumbnailBorderRadius: 20,
  thumbnailBorderColor: 'white',
  thumbnailPadding: 0,
  thumbnailGap: 10,
  backgroundColor: '',
  captionsPosition: LightboxCaptionsPosition.BOTTOM,
  captionFontFamily: 'Roboto',
  captionColor: 'White',
  imageAnimation: LightboxImageAnimation.BLUR,
};

const carouselMockSettings: ICarouselSettings = {
  width: 800,
  height: 800,
  gap: 20,
  backgroundColor: '',
  loop: false,
  pagination: true,
  effects: 'coverflow',
  autoplay: false,
  delay: 3000,
  playAndPouseAllowed: false,
  slidesDepth: -100,
  scale: 1.2,
  rotate: 80,
  modifier: 0.2,
  imagesCount: 4,
  spaceBetween: 10,
  centeredSlides: true,
  stretch: 0,
  slideShadows: true,
  shadow: true,
  shadowOffset: 20,
  shadowOpacity: 9,
  perSlideOffset: 8,
  rotateCard: false,
};
export {
  carouselMockSettings,
  generalMockSettings,
  lightboxMockSettings,
  masonryMockSettings,
  mosaicMockSettings,
  slideshowMockSettings,
  thumbnailMockSettings,
};
