import {
  BlogViewImagePosition,
  HoverEffect,
  IBlogSettings,
  ICardsSettings,
  ICarouselSettings,
  ICubeSettings,
  IGeneralSettings,
  IJustifiedSettings,
  ILightboxSettings,
  ImageClickAction,
  IMasonrySettings,
  IMosaicSettings,
  ISlideshowSettings,
  IThumbnailSettings,
  LightboxImageAnimation,
  LightboxTextPosition,
  LightboxThumbnailsPosition,
  PaginationButtonShape,
  PaginationType,
  SizeTypeHeight,
  SizeTypeWidth,
  TextsAlignment,
  ThumbnailTitlePosition,
  TitleAlignment,
  TitleSource,
  TitlePosition,
  TitleVisibility,
  DescriptionSource,
  CaptionSource,
} from 'data-structures';

const thumbnailMockSettings: IThumbnailSettings = {
  width: 150,
  height: 150,
  columns: 5,
  gap: 10,
  backgroundColor: 'White',
  containerPadding: 0,
  padding: 10,
  paddingColor: 'Skyblue',
  borderRadius: 5,
  titlePosition: ThumbnailTitlePosition.BOTTOM,
  titleSource: TitleSource.TITLE,
  titleAlignment: TitleAlignment.LEFT,
  titleVisibility: TitleVisibility.NONE,
  titleFontFamily: 'Roboto',
  titleColor: 'Black',
  titleFontSize: 20,
  hoverEffect: HoverEffect.NONE,
  paginationType: PaginationType.SIMPLE,
  showCaption: false,
  captionSource: CaptionSource.CAPTION,
  captionFontSize: 18,
  captionFontColor: 'Grey',
};

const mosaicMockSettings: IMosaicSettings = {
  width: 70,
  gap: 5,
  backgroundColor: '',
  containerPadding: 0,
  padding: 5,
  paddingColor: '',
  columns: 5,
  borderRadius: 5,
  titlePosition: TitlePosition.BOTTOM,
  titleSource: TitleSource.TITLE,
  titleAlignment: TitleAlignment.LEFT,
  titleVisibility: TitleVisibility.NONE,
  titleFontFamily: 'Roboto',
  titleColor: 'Black',
  titleFontSize: 20,
  hoverEffect: HoverEffect.BLUR,
  paginationType: PaginationType.SIMPLE,
  showCaption: false,
  captionSource: CaptionSource.CAPTION,
  captionFontSize: 18,
  captionFontColor: 'Grey',
};
const justifiedMockSettings: IJustifiedSettings = {
  width: 70,
  gap: 5,
  backgroundColor: '',
  containerPadding: 0,
  padding: 5,
  paddingColor: '',
  rowHeight: 250,
  borderRadius: 5,
  titlePosition: TitlePosition.BOTTOM,
  titleSource: TitleSource.TITLE,
  titleAlignment: TitleAlignment.LEFT,
  titleVisibility: TitleVisibility.NONE,
  titleFontFamily: 'Roboto',
  titleColor: 'Black',
  titleFontSize: 20,
  hoverEffect: HoverEffect.BLUR,
  paginationType: PaginationType.SIMPLE,
  showCaption: false,
  captionSource: CaptionSource.CAPTION,
  captionFontSize: 18,
  captionFontColor: 'Grey',
};

const masonryMockSettings: IMasonrySettings = {
  width: 70,
  gap: 5,
  backgroundColor: '',
  containerPadding: 0,
  padding: 5,
  paddingColor: '',
  columns: 5,
  borderRadius: 5,
  titlePosition: TitlePosition.BOTTOM,
  titleSource: TitleSource.TITLE,
  titleAlignment: TitleAlignment.LEFT,
  titleVisibility: TitleVisibility.NONE,
  titleFontFamily: 'Roboto',
  titleColor: 'Black',
  titleFontSize: 20,
  hoverEffect: HoverEffect.BLUR,
  paginationType: PaginationType.SIMPLE,
  showCaption: false,
  captionSource: CaptionSource.CAPTION,
  captionFontSize: 18,
  captionFontColor: 'Grey',
};

const slideshowMockSettings: ISlideshowSettings = {
  width: 800,
  height: 800,
  isInfinite: false,
  padding: 15,
  autoplay: false,
  slideDuration: 3000,
  backgroundColor: '',
  textPosition: LightboxTextPosition.BOTTOM,
  textFontFamily: 'Roboto',
  textColor: 'White',
  imageAnimation: LightboxImageAnimation.BLUR,
  thumbnailsPosition: LightboxThumbnailsPosition.BOTTOM,
  thumbnailWidth: 80,
  thumbnailHeight: 80,
  thumbnailBorder: 2,
  thumbnailBorderRadius: 20,
  thumbnailBorderColor: 'white',
  thumbnailPadding: 0,
  thumbnailGap: 10,
  isSlideshowAllowed: true,
  showTitle: true,
  titleFontSize: 20,
  titleAlignment: TitleAlignment.LEFT,
  showDescription: true,
  descriptionFontSize: 16,
  descriptionMaxRowsCount: 5,
  isFullCoverImage: false,
  titleSource: TitleSource.TITLE,
  descriptionSource: DescriptionSource.DESCRIPTION,
  showCaption: false,
  captionSource: CaptionSource.CAPTION,
  captionFontSize: 18,
  captionFontColor: 'Grey',
};

const generalMockSettings: IGeneralSettings = {
  orderBy: 'default',
  orderDirection: 'asc',
  itemsPerPage: 8,
  activeButtonColor: 'blue',
  inactiveButtonColor: 'inherit',
  paginationButtonShape: PaginationButtonShape.CIRCULAR,
  loadMoreButtonColor: 'blue',
  paginationTextColor: 'green',
  clickAction: ImageClickAction.LIGHTBOX,
  openUrlInNewTab: false,
};

const lightboxMockSettings: ILightboxSettings = {
  isFullscreen: false,
  width: 800,
  height: 800,
  areControlButtonsShown: false,
  isInfinite: false,
  padding: 15,
  canShare: false,
  canDownload: true,
  canZoom: true,
  isFullscreenAllowed: false,
  isSlideshowAllowed: false,
  autoplay: false,
  slideDuration: 3000,
  thumbnailsPosition: LightboxThumbnailsPosition.BOTTOM,
  thumbnailWidth: 80,
  thumbnailHeight: 80,
  thumbnailBorder: 2,
  thumbnailBorderRadius: 20,
  thumbnailBorderColor: 'white',
  thumbnailPadding: 0,
  thumbnailGap: 10,
  backgroundColor: '',
  textPosition: LightboxTextPosition.BOTTOM,
  textFontFamily: 'Roboto',
  textColor: 'White',
  imageAnimation: LightboxImageAnimation.BLUR,
  showTitle: true,
  titleFontSize: 20,
  titleAlignment: TitleAlignment.LEFT,
  showDescription: true,
  descriptionFontSize: 16,
  descriptionMaxRowsCount: 5,
  titleSource: TitleSource.TITLE,
  descriptionSource: DescriptionSource.DESCRIPTION,
  showCaption: false,
  captionSource: CaptionSource.CAPTION,
  captionFontSize: 18,
  captionFontColor: 'Grey',
};

const cubeMockSettings: ICubeSettings = {
  width: 300,
  height: 300,
  backgroundColor: '',
  padding: 0,
  isInfinite: false,
  autoplay: false,
  slideDuration: 3000,
  shadow: true,
};

const carouselMockSettings: ICarouselSettings = {
  width: 200,
  height: 250,
  backgroundColor: '',
  padding: 0,
  autoplay: false,
  slideDuration: 3000,
  playAndPauseAllowed: false,
  scale: 0.1,
  imagesCount: 3,
  spaceBetween: -10,
};

const cardsMockSettings: ICardsSettings = {
  width: 300,
  height: 300,
  perSlideOffset: 2,
  navigationButton: false,
  playAndPauseAllowed: false,
  autoplay: false,
  slideDuration: 3000,
};

const blogMockSettings: IBlogSettings = {
  imageWidth: 50,
  imageHeight: 100,
  spacing: 0,
  backgroundColor: 'White',
  containerPadding: 0,
  imageRadius: 0,
  hoverEffect: HoverEffect.NONE,
  textVerticalAlignment: TextsAlignment.CENTER,
  textFontFamily: 'Roboto',
  titleSource: TitleSource.TITLE,
  descriptionSource: DescriptionSource.DESCRIPTION,
  titleColor: 'black',
  descriptionColor: 'black',
  titleFontSize: 20,
  descriptionFontSize: 16,
  buttonText: 'SEE MORE',
  buttonAlignment: TitleAlignment.LEFT,
  buttonColor: '#22eaaa',
  buttonTextColor: '#fff',
  buttonFontSize: 16,
  imageHeightType: SizeTypeHeight.VH,
  imageWidthType: SizeTypeWidth.PERCENT,
  showButton: true,
  openInNewTab: false,
  showTitle: true,
  showDescription: true,
  textHorizontalSpacing: 30,
  textVerticalSpacing: 30,
  paginationType: PaginationType.SIMPLE,
  titleAlignment: TitleAlignment.LEFT,
  descriptionMaxRowsCount: 5,
  imagePosition: BlogViewImagePosition.STAGGERED,
  showCaption: false,
  captionSource: CaptionSource.CAPTION,
  captionFontSize: 18,
  captionFontColor: 'Grey',
};

export {
  blogMockSettings,
  cardsMockSettings,
  carouselMockSettings,
  cubeMockSettings,
  generalMockSettings,
  justifiedMockSettings,
  lightboxMockSettings,
  masonryMockSettings,
  mosaicMockSettings,
  slideshowMockSettings,
  thumbnailMockSettings,
};
